### ISSUE TITLE
Language Name Clash :)

### ISSUE THREAD

**Issue by NyproTheGeek** [TheAustinSeven/Astro-Manifesto#1]
Hi! Seems we have a language name clash. I may have to change my language name... again! 
Irrespective, I would appreciate if you check out my own idea of [Astro ](https://github.com/NyproTheGeek/Astro)and I would like to also see your syntax proposal. Your syntax folder is empty.

**Comment by TheAustinSeven** [comment]
Yeah, the overall idea of the language you are building sounds similar enough to what I am building, it may be worth looking if they could be combined(if that is something you would be interested in). I will post the syntax samples very soon.

**Comment by TheAustinSeven** [comment]
I checked out your language proposal. It looks almost exactly like python, which is fairly different from what I am building. I don't really think these languages are compatible whatsoever, purely from a syntactic standpoint. Also, in case you didn't know, google is already working on a python compiler, so that would probably do what you want. If you do decide to continue building your version, I would very much appreciate if you changed the name, given that I have been working with this title for some time now. If you would instead like to contribute to the development of this Astro, then reopen this issue and I will let you know when I am ready to welcome contributors.
